### ISSUE TITLE
What are the differences between the models?

### ISSUE THREAD

**Issue by psoulos** [fducau/infoVAE#1]
vae.py, vae_1.py, and vae_half.py all contain mutual information in the cost function. What are the differences between these models?

**Comment by fducau** [comment]
Hi @psoulos, this was a research repo and I did not take the necessary time to document it properly so first suggestion is use with care. 
Apart from that, if I'm not mistaken, in the case of vae_1.py the mutual information is enforced between the entire z (latent code) vector, while in vae_half.py the mutual information is only enforced in some dimensions on the latent code and not in others. 
The convetion when enforcing MI in one part of the code is to call this part of the latent representation '**c**' and call the part in which the MI is not enforced '**z**'

Hope it helps!

**Comment by psoulos** [comment]
Thanks! It looks like mutual information is calculated differently in [vae.py](https://github.com/fducau/infoVAE/blob/master/vae.py#L204) and [vae_1.py](https://github.com/fducau/infoVAE/blob/master/vae_1.py#L208). Do you remember the reason for this?

**Comment by psoulos** [comment]
Hi @fducau, do you remember what vae.py was used for? It looks like vae_1.py and vae_half.py follow the formulas from the paper. I just want to make sure I'm not missing something.

Thanks!

**Comment by fducau** [comment]
Hi @psoulos , vae and vae_1.py should behave similar. We are just using there a different way to compute the same MI term.
